---
title: "milestone2"
author: "Jiacheng"
date: "2022-11-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(shiny)
library(shinyWidgets)
library(dslabs)
library(plotly)
library(knitr)
library(tidyverse)
#library(tsibble)
#library(lubridate)
#library(sf)
#library(tmap)
#library(terra)
#library(ceramic)
#library(tsibble)
#library(tsibbledata)
#library(ggHoriPlot)
#library(ggstream)
#library(colorspace)
#library(ggalluvial)
#library(scales)
```


```{r}
life<-read.csv("/Users/yujiacheng/Desktop/Data_Visualization_Project/life_expectancy_data.csv")
colnames(life)[colnames(life)=="Life.expectancy"] <- "life_expectancy"
colnames(life)[colnames(life)=="Adult.Mortality"] <- "adult_mortality"
colnames(life)[colnames(life)=="infant.deaths"] <- "infant_deaths"
life
```

```{r}
continent= read.csv("/Users/yujiacheng/Desktop/Data_Visualization_Project/Continents.csv")
life=merge(continent,life)
life
```


```{r}
life <- life %>% 
  pivot_longer(cols = c(life_expectancy, adult_mortality,infant_deaths), 
                 names_to = "data", values_to = "value")
life
```

```{r}
ui <- fluidPage(
    titlePanel("Health condition in 2000-2015"),
    sidebarLayout(
        sidebarPanel(
            selectizeInput("countryInput", "Country",
                           choices = unique(life$Country),  
                           selected="United States of America", multiple =FALSE), 

            checkboxGroupInput("continentInput", "Continent",
                               choices = c("Africa",
                                           "Asia",
                                           "Europe",
                                           "North America",
                                           "Oceania",
                                           "South America"),
                               selected = c("Africa",
                                           "Asia",
                                           "Europe",
                                           "North America",
                                           "Oceania",
                                           "South America")),

            sliderInput("yearInput", "Year", min=2000, max=2015, 
                        value=c(2000, 2015), sep=""),
            radioGroupButtons("dataInput", "Data",
        choiceNames = list("Life Expectancy", "Adult Mortality","Infant Deaths"),
        choiceValues = list("life_expectancy", "adult_mortality","infant_deaths"))
        ),  
        
        mainPanel(
            plotOutput("lifeplot"),
            br(), br(),
            verbatimTextOutput("stats"), 
            br(), br(),
            plotlyOutput("distplot")
        ) 
    )   
)   

server <- function(input, output) {
    d <- reactive({
        life %>%
            filter(Country == input$countryInput,
                   Continent %in% input$continentInput,
                   Year >= input$yearInput[1],
                   Year <= input$yearInput[2],
                   data == input$dataInput)
    }) 
    
    output$lifeplot <- renderPlot({
        ggplot(d(), aes(x=Year, y = value, color=Continent)) +
            geom_line() + 
            theme_bw() +
            xlab("Year") +
            ylab(input$dataInput) +
            ggtitle("Health Condition over time")
    })
    
    output$stats <- renderPrint({
        aggregate(value ~ Continent, data = d(), sum)
    })
    
    output$distplot <- renderPlotly({
        
        box <- plot_ly(d(), y = ~value,
                       color = ~ Continent, type = "box")  %>%
            layout(title = "Distribution of Health Condition over different years",
                   yaxis = list(title=input$dataInput))
    })
}

shinyApp(ui=ui, server=server)
```



```{r}
ui <- fluidPage(
    titlePanel("Health condition in 2000-2015"),
    sidebarLayout(
        sidebarPanel(
            selectizeInput("countryInput", "Country",
                           choices = unique(life$Country),  
                           selected="United States of America", multiple =FALSE), 

            checkboxGroupInput("statusInput", "Status",
                               choices = c("Developing",
                                           "Developed"),
                               selected = c("Developing","Developed")),

            sliderInput("yearInput", "Year", min=2000, max=2015, 
                        value=c(2000, 2015), sep=""),
            radioGroupButtons("dataInput", "Data",
        choiceNames = list("Life Expectancy", "Adult Mortality","Infant Deaths"),
        choiceValues = list("life_expectancy", "adult_mortality","infant_deaths"))
        ),  
        
        mainPanel(
            plotOutput("lifeplot"),
            br(), br(),
            verbatimTextOutput("stats"), 
            br(), br(),
            plotlyOutput("distplot")
        ) 
    )   
)   

server <- function(input, output) {
    d <- reactive({
        life %>%
            filter(Country == input$countryInput,
                   Status %in% input$statusInput,
                   Year >= input$yearInput[1],
                   Year <= input$yearInput[2],
                   data == input$dataInput)
    }) 
    
    output$lifeplot <- renderPlot({
        ggplot(d(), aes(x=Year, y = value, color=Status)) +
            geom_line() + 
            theme_bw() +
            xlab("Year") +
            ylab(input$dataInput) +
            ggtitle("Health Condition over time")
    })
    
    output$stats <- renderPrint({
        aggregate(value ~ Status, data = d(), sum)
    })
    
    output$distplot <- renderPlotly({
        
        box <- plot_ly(d(), y = ~value,
                       color = ~ Status, type = "box")  %>%
            layout(title = "Distribution of Health Condition over different years",
                   yaxis = list(title=input$dataInput))
    })
}

shinyApp(ui=ui, server=server)
```

